routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/


Route::group(['as' => 'admin.'], function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');
    Route::resource('auctions', 'AuctionController')->only(['destroy', 'edit', 'show']);
    Route::match(['GET', 'POST'], '/profile', 'AdminController@adminProfileChange')->name('profile');
    Route::post('products/add-group', 'ProductController@addGroup')->name('products.add_group');
    Route::get('products/{id}/duplicate', 'ProductController@duplicate')->name('products.duplicate');
    Route::post('banner/change', 'SliderController@changeBanner')->name('banner.change');
    Route::resource('products', 'ProductController')->only([
        'index', 'edit', 'update', 'create', 'store', 'destroy'
    ]);

    Route::resource('users', 'UserController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::resource('sliders', 'SliderController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('howitworks', 'HowitworkController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('questions', 'QuestionController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('reviews', 'ReviewController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('video', 'VideoController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('packages', 'PackageController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('orders', 'OrderController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::delete('bots/name/{id}/delete', 'BotController@nameDelete')->name('bots.destroy.name');
    Route::resource('bots', 'BotController')->only([
        'index', 'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::group(['as' => 'settings.', 'prefix' => 'settings'], function () {
        Route::match(['GET', 'POST'], '/mail', 'AdminController@mailConfig')->name('mail');
        Route::match(['GET', 'POST'], '/site', 'AdminController@siteConfig')->name('site');
        Route::get('/mailing', 'AdminController@mailing')->name('mailing');
        Route::match(['GET','PUT'],'/access', 'AdminController@access')->name('access');
    });
    Route::resource('role', 'RoleController')->only([
        'store', 'update', 'destroy'
    ]);
    Route::get('/mailings/{mailing}/send', 'MailingController@send')->name('mailings.send');
    Route::resource('mailings', 'MailingController')->only([
        'create', 'store', 'edit', 'update', 'destroy', 'send'
    ]);
    Route::group(['as' => 'pages.', 'prefix' => 'pages', 'namespace' => 'Pages'], function () {
        Route::post('/seo/{id}/update', 'PageController@seoUpdate')->name('seo.update');
        Route::get('/footer', 'PageController@footer')->name('footer');
        Route::post('/footer/linkOnOff', 'PageController@linkOnOff')->name('footer.linkOnOff');
        Route::post('/footer/linkPosition', 'PageController@linkPosition')->name('footer.linkPosition');
        Route::post('/footer/linkFloat', 'PageController@linkFloat')->name('footer.linkFloat');
        Route::post('/footer/crud', 'PageController@footerLinkCrud')->name('footer.crud');
        Route::get('/dynamic-page/image/browse', 'PageController@footerPageBrowseImg')->name('ckeditor.browse');
        Route::post('/dynamic-page/upload/image', 'PageController@footerPageUploadImg')->name('ckeditor.upload');
        Route::get('/home', 'PageController@homePage')->name('home');
        Route::get('/howitworks', 'PageController@howItWorksPage')->name('howitworks');
        Route::get('/reviews', 'PageController@reviewsPage')->name('reviews');
        Route::get('/feedback', 'PageController@feedbackPage')->name('feedback');
        Route::get('/coupon', 'PageController@couponPage')->name('coupon');
        Route::get('/order', 'PageController@orderPage')->name('order');
        Route::put('/update/{slug}', 'PageController@updatePage')->name('update');
        Route::put('/update_ac_content', 'PageController@updateAccordionBehindFooter')->name('updateAccordionBehindFooter');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/sitemap.xml', 'SitemapXmlController')->name('sitemap');
Route::group(['as' => 'site.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/how-it-works', 'HomeController@howItWorks')->name('how_it_works');
    Route::match(['GET', 'POST'], '/feedback', 'HomeController@feedback')->name('feedback');
    Route::get('/reviews', 'HomeController@reviews')->name('reviews');
    Route::post( '/reviews', 'HomeController@reviews')->name('reviews.store')->middleware(['auth']);
    Route::get('/coupon', 'HomeController@coupon')->name('coupon');
    Route::get('/cookie-agree', 'HomeController@cookieAgree')->name('cookie_agree');
    Route::get('/order-status', 'HomeController@orderStatus')->name('orderStatus');
    Route::get('/success', 'HomeController@success')->name('checkout.success');
    Route::get('/fail', 'HomeController@fail')->name('checkout.fail');
});

Route::group(['prefix' => '/cabinet', 'middleware' => 'auth', 'as' => 'profile.', 'namespace' => 'User'], function () {
    Route::match(['GET', 'POST'], '/', 'ProfileController@index')->name('index');
    Route::match(['GET', 'POST'], '/personal', 'ProfileController@personalData')->name('personal');
    Route::get('/balance', 'ProfileController@balance')->name('balance');
    Route::get('/orders', 'ProfileController@orders')->name('orders');
    Route::get('/auction-history', 'ProfileController@auctionsHistory')->name('auctions_history');
    Route::get('/referral-program', 'ProfileController@referralProgram')->name('referral_program');
    Route::match(['GET', 'POST'], '/code-email-confirm', 'ProfileController@codeEmailConfirm')->name('email_code_confirm');
    Route::post('/{id}/subscribe', 'ProfileController@subscribe')->name('subscribe');
});

Route::group(['as' => 'auction.',], function () {
    Route::get('/{id}/auction', 'AuctionController@auction')->name('index');
    Route::post('/{auction_id}/add-favorite', 'AuctionController@addFavorite')->name('add_favorite')->middleware('auth');
    Route::post('/{id}/auto_bid', 'AuctionController@autoBid')->name('auto_bid')->middleware(['auth', 'banned']);
    Route::post('/change-status/{id?}', 'AuctionController@changeStatus')->name('change_status');
});

Route::group(['prefix' => '/payment', 'middleware' => ['auth', 'banned'], 'as' => 'payment.', 'namespace' => 'Payments'], function () {
    Route::post('/buy-coupon', 'CouponController@buy')->name('coupon.buy');
    Route::post('/buy-auction', 'AuctionController@buy')->name('auction.buy')->middleware('order');
    Route::get('/{id}/order', 'AuctionController@order')->name('auction.order')->middleware('order');
    Route::post('/{id}/check-order', 'AuctionController@checkOrder')->name('check.order')->middleware('order');
    Route::get('/{id}/win-info', 'AuctionController@winInfo')->name('win.info')->middleware('order');
});

Route::group(['prefix' => '/reset', 'as' => 'reset.', 'namespace' => 'PasswordReset'], function () {
    Route::get('/password', 'ResetController@reset')->name('password.sms');
    Route::post('/check-phone-number', 'ResetController@checkPhone')->name('check.phone');
    Route::get('/password-change', 'ResetController@passwordChange')->name('password.change');
    Route::post('/password-change', 'ResetController@passwordChangeSuccess')->name('password.change.success');
});

Route::group(['middleware' => ['auth', 'banned']], function () {
    Route::get('/bet/{id}', 'BetController')->name('bet');
});

Route::get('/{slug?}', 'HomeController@dynamicPage')->where(['slug' => '^(?!admin.*$).*']);

resources/views/admin/access.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <h1 class="h3 mb-2 text-gray-800">Доступы</h1>
        <div class="card shadow mb-4">
            <div class="card-body">
                <form class="form-inline" method="POST" action="{{route('admin.role.store')}}">
                    @csrf
                    <div class="form-group mb-2">
                        <p class="m-0">Добавить роль</p>
                    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="roleName" class="sr-only">Название</label>
                        <input name="name" type="text" class="form-control" id="roleName" placeholder="Название">
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Добавить</button>
                </form>
                @error('name') <small class="text-danger">{{$message}}</small> @enderror
                <div class="table-responsive">
                    <table class="table table-striped nowrap" width="100%" cellspacing="0" align="center"
                           id="role_table">
                        <thead>
                        <tr>
                            <th>Роль</th>
                            <th>Страницы</th>
                            <th>Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($roles as $role)
                            <tr>
                                <th>{{ucfirst($role->name)}}</th>
                                <th>
                                    <ul class="list-group">
                                        @foreach($pages as $page)
                                            @php $exists = $role->adminPages()->where('id',$page->id)->exists() @endphp
                                            <li class="list-group-item d-flex justify-content-between">
                                                <label for="page_{{$page->id}}">{{$page->name}}</label>
                                                <button type='button'
                                                        class='btn btn-sm btn-toggle @if($exists) active @endif'
                                                        id="page_{{$page->id}}"
                                                        data-toggle='button'
                                                        @if($exists)
                                                        aria-pressed='true'
                                                        @else
                                                        aria-pressed='false'
                                                        @endif
                                                        onclick='oNoFF("{{route('admin.settings.access')}}",{role_id:"{{$role->id}}",admin_page_id:"{{$page->id}}"},`PUT`)'>
                                                    <span class='handle'></span>
                                                </button>
                                            </li>
                                        @endforeach
                                    </ul>
                                </th>
                                <th>
                                    <button type="button" class="btn btn-danger" data-toggle="modal"
                                            data-target="#resourceModal"
                                            data-action="{{route('admin.role.destroy',$role->id)}}">
                                        удалить
                                    </button>
                                </th>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('content')
    <div class="modal fade" tabindex="1" id="cardModal" role="dialog" aria-labelledby="cardModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="cardModalLabel"></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыт</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <h1 class="h3 mb-2 text-gray-800">Аукционы</h1>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row text-center">
                    <div class="col-md-6">
                        <span class="m-0 font-weight-bold text-primary">Всего аукционов в базе: <span
                                class="text-dark">{{$auctionsInfo['auction_count']}}</span></span>
                    </div>
                    <div class="col-md-6">
                        <span class="m-0 font-weight-bold text-primary">На сайте: <span
                                id="visibly_count"
                                class="text-dark">{{$auctionsInfo['active_count']}}</span></span>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <p>Фильтр по аукционам </p>
                    </div>
                    <div class="input-group mb-3 col-md-6">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Статус</label>
                        </div>
                        <select class="custom-select" id="inputGroupSelect01">
                            <option selected>Все</option>
                            <option>Активный</option>
                            <option>Скоро начало</option>
                            <option>Ошибка</option>
                            <option>Победил бот</option>
                            <option>Победил игрок</option>
                            <option>Не состоялся</option>
                        </select>
                    </div>
                    <div class="input-group mb-3 col-md-6">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect02">На сайте</label>
                        </div>
                        <select class="custom-select" id="inputGroupSelect02">
                            <option selected>Все</option>
                            <option>да</option>
                            <option>нет</option>
                        </select>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-striped nowrap" width="100%" cellspacing="0" align="center"
                           id="product_table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Фото</th>
                            <th>Наименование</th>
                            <th>Статус</th>
                            <th>Ставок</th>
                            <th>Бонусов</th>
                            <th>Бот</th>
                            <th>Старт</th>
                            <th>Финиш</th>
                            <th>На сайте</th>
                            <th>Действие</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script>
            $(document).ready(function () {
                let table = $('#product_table').DataTable({
                    aLengthMenu: [
                        [100, -1],
                        [100, "Все"]
                    ],
                    processing: true,
                    serverSide: true,
                    ajax: '{{ route('admin.dashboard') }}',
                    "language": {
                        "url": "{{url('/datatables/lang/Russian.json')}}"
                    },
                    columns: [
                        {data: 'id', name: 'id'},
                        {data: 'img_1', name: 'img_1', orderable: false, searchable: false},
                        {
                            data: 'title', name: 'title', "render": function (data, type, full) {
                                return `<a href="/${full.id}/auction">${data}</a>`;
                            }
                        },
                        {data: 'status', name: 'status'},
                        {data: 'bet', name: 'bet'},
                        {data: 'bonus', name: 'bonus'},
                        {data: 'bot', name: 'bot'},
                        {data: 'start', name: 'start'},
                        {data: 'end', name: 'end'},
                        {data: 'active', name: 'active'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ]
                }).on('page.dt', function () {
                    $('html, body').animate({
                        scrollTop: 0
                    }, 2000);
                });
                $('#inputGroupSelect01').on('change', function () {
                    let val = (this.value === 'Все') ? null : this.value;
                    table.columns(3).search(val ? '^' + val + '$' : '', true, false).draw();
                });
                $('#inputGroupSelect02').on('change', function () {
                    let val = (this.value === 'Все') ? null : this.value;
                    table.columns(9).search(val ? '^' + val + '$' : '', true, false).draw();
                });
            });
            $(document).on('click', '[data-target="#cardModal"]', function () {
                let url = $(this).data('href');
                let method = 'GET';
                let data = null;
                let modal = $($(this).data('target'));
                modal.find('.modal-body').html('');
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: method,
                    url: url,
                    data: data,
                    success: (data) => {
                        if (data.success && data.html) {
                            modal.find('.modal-body').html(data.html);
                            modal.find('#cardModalLabel').text(data.title);
                            $('#auction_card').DataTable({
                                paging: false,
                                "language": {
                                    "url": "{{url('/datatables/lang/Russian.json')}}"
                                },
                            })
                        }
                    },
                    error: (error) => {
                        console.log(error)
                    }
                });
            })
        </script>
    @endpush
@endsection

resources/views/admin/mailing.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <h1 class="h3 mb-2 text-gray-800">Рассылки</h1>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Сервисные рассылки</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" width="100%" cellspacing="0" align="center">
                        <thead>
                        <tr>
                            <th>Тема</th>
                            <th>Текст</th>
                            <th>Вкл./Выкл.</th>
                            <th>Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($mailings['no_ads'] as $mailing)
                            <tr>
                                <td>
                                    <p class="name">{{$mailing->subject}}</p>
                                </td>
                                <td>
                                    <p class="name">{{$mailing->text}}</p>
                                </td>
                                <td>
                                    <button type="button"
                                            class="btn btn-sm btn-toggle @if($mailing->visibly) active @endif"
                                            data-toggle="button" @if($mailing->visibly) aria-pressed="true"
                                            @else aria-pressed="false" @endif  autocomplete="off"
                                            onclick='oNoFF("{{route('admin.mailings.update',[$mailing->id])}}",{visibly:($(this).attr("aria-pressed") === "true" ? 0 : 1),},"PUT")'>
                                        <span class="handle"></span>
                                    </button>
                                </td>
                                <td>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.mailings.edit',[$mailing->id])}}" class="btn btn-info btn-icon-split">
                                            <span class="icon text-white-50">
                                              <i class="fas fa-info-circle"></i>
                                            </span>
                                            <span class="text">изменить</span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Рекламные рассылки</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" width="100%" cellspacing="0" align="center">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Тема</th>
                            <th>Текст</th>
                            <th>Действие</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th colspan="4">
                                <a href="{{route('admin.mailings.create')}}" class="btn btn-success btn-icon-split float-right">
                                            <span class="icon text-white-50">
                                              <i class="fas fa-check"></i>
                                            </span>
                                    <span class="text">добавить</span>
                                </a>
                            </th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($mailings['ads'] as $mailing)
                            <tr>
                                <td>
                                    <p class="name">{{$mailing->title}}</p>
                                </td>
                                <td>
                                    <p class="name">{{$mailing->subject}}</p>
                                </td>
                                <td>
                                    <p class="name">{{$mailing->text}}</p>
                                </td>
                                <td>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.mailings.edit',[$mailing->id])}}" class="btn btn-info btn-icon-split">
                                            <span class="icon text-white-50">
                                              <i class="fas fa-info-circle"></i>
                                            </span>
                                            <span class="text">изменить</span>
                                        </a>
                                        <button class="btn btn-danger btn-icon-split"
                                                type="button"
                                                data-toggle="modal"
                                                data-target="#resourceModal"
                                                data-action="{{route('admin.mailings.destroy',[$mailing->id])}}">
                                            <span class="icon text-white-50">
                                              <i class="fas fa-trash"></i>
                                            </span>
                                            <span class="text">удалить</span>
                                        </button>
                                        <a href="{{route('admin.mailings.send',[$mailing->id])}}" class="btn btn-success btn-icon-split">
                                            <span class="icon text-white-50">
                                              <i class="fas fa-check"></i>
                                            </span>
                                            <span class="text">Отправить</span>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Администратор</h6>
            </div>
            <div class="card-body">
                <form action="{{route('admin.profile')}}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label for="phone" class="col-sm-2 col-form-label">Логин</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control mask" id="phone" placeholder="телефон" name="phone" value="{{old('phone')??auth()->user()->phone}}">
                            @error('phone')
                            <small class="text-danger">
                                {{$message}}
                            </small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="current_password" class="col-sm-2 col-form-label">Старый пароль</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="current_password" name="current_password" placeholder="старый пароль">
                            @error('current_password')
                            <small class="text-danger">
                                {{$message}}
                            </small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="new_password" class="col-sm-2 col-form-label">Новый пароль</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="new_password" name="new_password" placeholder="новый пароль">
                            @error('new_password')
                            <small class="text-danger">
                                {{$message}}
                            </small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="new_confirm_password" class="col-sm-2 col-form-label">Подтвердите пароль</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="new_confirm_password" name="new_confirm_password" placeholder="подтвердите пароль">
                            @error('new_confirm_password')
                            <small class="text-danger">
                                {{$message}}
                            </small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-outline-success float-right">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection