routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/


Route::group(['as' => 'admin.'], function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');
    Route::resource('auctions', 'AuctionController')->only(['destroy', 'edit', 'show']);
    Route::match(['GET', 'POST'], '/profile', 'AdminController@adminProfileChange')->name('profile');
    Route::post('products/add-group', 'ProductController@addGroup')->name('products.add_group');
    Route::get('products/{id}/duplicate', 'ProductController@duplicate')->name('products.duplicate');
    Route::post('banner/change', 'SliderController@changeBanner')->name('banner.change');
    Route::resource('products', 'ProductController')->only([
        'index', 'edit', 'update', 'create', 'store', 'destroy'
    ]);

    Route::resource('users', 'UserController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::resource('sliders', 'SliderController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('howitworks', 'HowitworkController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('questions', 'QuestionController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('reviews', 'ReviewController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('video', 'VideoController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('packages', 'PackageController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('orders', 'OrderController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::delete('bots/name/{id}/delete', 'BotController@nameDelete')->name('bots.destroy.name');
    Route::resource('bots', 'BotController')->only([
        'index', 'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::group(['as' => 'settings.', 'prefix' => 'settings'], function () {
        Route::match(['GET', 'POST'], '/mail', 'AdminController@mailConfig')->name('mail');
        Route::match(['GET', 'POST'], '/site', 'AdminController@siteConfig')->name('site');
        Route::get('/mailing', 'AdminController@mailing')->name('mailing');
        Route::match(['GET','PUT'],'/access', 'AdminController@access')->name('access');
    });
    Route::resource('role', 'RoleController')->only([
        'store', 'update', 'destroy'
    ]);
    Route::get('/mailings/{mailing}/send', 'MailingController@send')->name('mailings.send');
    Route::resource('mailings', 'MailingController')->only([
        'create', 'store', 'edit', 'update', 'destroy', 'send'
    ]);
    Route::group(['as' => 'pages.', 'prefix' => 'pages', 'namespace' => 'Pages'], function () {
        Route::post('/seo/{id}/update', 'PageController@seoUpdate')->name('seo.update');
        Route::get('/footer', 'PageController@footer')->name('footer');
        Route::post('/footer/linkOnOff', 'PageController@linkOnOff')->name('footer.linkOnOff');
        Route::post('/footer/linkPosition', 'PageController@linkPosition')->name('footer.linkPosition');
        Route::post('/footer/linkFloat', 'PageController@linkFloat')->name('footer.linkFloat');
        Route::post('/footer/crud', 'PageController@footerLinkCrud')->name('footer.crud');
        Route::get('/dynamic-page/image/browse', 'PageController@footerPageBrowseImg')->name('ckeditor.browse');
        Route::post('/dynamic-page/upload/image', 'PageController@footerPageUploadImg')->name('ckeditor.upload');
        Route::get('/home', 'PageController@homePage')->name('home');
        Route::get('/howitworks', 'PageController@howItWorksPage')->name('howitworks');
        Route::get('/reviews', 'PageController@reviewsPage')->name('reviews');
        Route::get('/feedback', 'PageController@feedbackPage')->name('feedback');
        Route::get('/coupon', 'PageController@couponPage')->name('coupon');
        Route::get('/order', 'PageController@orderPage')->name('order');
        Route::put('/update/{slug}', 'PageController@updatePage')->name('update');
        Route::put('/update_ac_content', 'PageController@updateAccordionBehindFooter')->name('updateAccordionBehindFooter');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/sitemap.xml', 'SitemapXmlController')->name('sitemap');
Route::group(['as' => 'site.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/how-it-works', 'HomeController@howItWorks')->name('how_it_works');
    Route::match(['GET', 'POST'], '/feedback', 'HomeController@feedback')->name('feedback');
    Route::get('/reviews', 'HomeController@reviews')->name('reviews');
    Route::post( '/reviews', 'HomeController@reviews')->name('reviews.store')->middleware(['auth']);
    Route::get('/coupon', 'HomeController@coupon')->name('coupon');
    Route::get('/cookie-agree', 'HomeController@cookieAgree')->name('cookie_agree');
    Route::get('/order-status', 'HomeController@orderStatus')->name('orderStatus');
    Route::get('/success', 'HomeController@success')->name('checkout.success');
    Route::get('/fail', 'HomeController@fail')->name('checkout.fail');
});

Route::group(['prefix' => '/cabinet', 'middleware' => 'auth', 'as' => 'profile.', 'namespace' => 'User'], function () {
    Route::match(['GET', 'POST'], '/', 'ProfileController@index')->name('index');
    Route::match(['GET', 'POST'], '/personal', 'ProfileController@personalData')->name('personal');
    Route::get('/balance', 'ProfileController@balance')->name('balance');
    Route::get('/orders', 'ProfileController@orders')->name('orders');
    Route::get('/auction-history', 'ProfileController@auctionsHistory')->name('auctions_history');
    Route::get('/referral-program', 'ProfileController@referralProgram')->name('referral_program');
    Route::match(['GET', 'POST'], '/code-email-confirm', 'ProfileController@codeEmailConfirm')->name('email_code_confirm');
    Route::post('/{id}/subscribe', 'ProfileController@subscribe')->name('subscribe');
});

Route::group(['as' => 'auction.',], function () {
    Route::get('/{id}/auction', 'AuctionController@auction')->name('index');
    Route::post('/{auction_id}/add-favorite', 'AuctionController@addFavorite')->name('add_favorite')->middleware('auth');
    Route::post('/{id}/auto_bid', 'AuctionController@autoBid')->name('auto_bid')->middleware(['auth', 'banned']);
    Route::post('/change-status/{id?}', 'AuctionController@changeStatus')->name('change_status');
});

Route::group(['prefix' => '/payment', 'middleware' => ['auth', 'banned'], 'as' => 'payment.', 'namespace' => 'Payments'], function () {
    Route::post('/buy-coupon', 'CouponController@buy')->name('coupon.buy');
    Route::post('/buy-auction', 'AuctionController@buy')->name('auction.buy')->middleware('order');
    Route::get('/{id}/order', 'AuctionController@order')->name('auction.order')->middleware('order');
    Route::post('/{id}/check-order', 'AuctionController@checkOrder')->name('check.order')->middleware('order');
    Route::get('/{id}/win-info', 'AuctionController@winInfo')->name('win.info')->middleware('order');
});

Route::group(['prefix' => '/reset', 'as' => 'reset.', 'namespace' => 'PasswordReset'], function () {
    Route::get('/password', 'ResetController@reset')->name('password.sms');
    Route::post('/check-phone-number', 'ResetController@checkPhone')->name('check.phone');
    Route::get('/password-change', 'ResetController@passwordChange')->name('password.change');
    Route::post('/password-change', 'ResetController@passwordChangeSuccess')->name('password.change.success');
});

Route::group(['middleware' => ['auth', 'banned']], function () {
    Route::get('/bet/{id}', 'BetController')->name('bet');
});

Route::get('/{slug?}', 'HomeController@dynamicPage')->where(['slug' => '^(?!admin.*$).*']);

app/Models/Order.php
<?php

namespace App\Models;

use App\Api\Invoice\Ofd;
use App\Models\Auction\Auction;
use App\Models\Pages\Package;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Order
 *
 * @property int $id
 * @property string|null $order_num
 * @property string|null $payment_type
 * @property string|null $price
 * @property int $status
 * @property bool $exchanged
 * @property int $user_id
 * @property int $auction_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\Auction\Auction $auction
 * @property-read User $user
 * @method static \Illuminate\Database\Eloquent\Builder|Order newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Order newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Order query()
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereAuctionId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereExchanged($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereOrderNum($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order wherePaymentType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereUserId($value)
 * @mixin \Eloquent
 * @property string|null $product_name
 * @property string|null $method
 * @property string $type
 * @property int|null $coupon_id
 * @property-read Package|null $coupon
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereCouponId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereMethod($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereProductName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereType($value)
 * @property string|null $receipt_id
 * @method static \Illuminate\Database\Eloquent\Builder|Order whereReceiptId($value)
 */
class Order extends Model
{
    const PENDING = 0;
    const SUCCESS = 1;
    const DECLINED = 2;
    const AUCTION = "auction";
    const COUPON = "coupon";
    protected $fillable = ['order_num', 'product_name', 'method', 'type', 'price', 'status', 'exchanged', 'user_id', 'auction_id', 'coupon_id', 'receipt_id'];
    protected $casts = ['status' => 'integer', 'exchanged' => 'boolean'];

    public function auction()
    {
        return $this->belongsTo(Auction::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function coupon()
    {
        return $this->belongsTo(Package::class);
    }

    public function price(): string
    {
        return Auction::moneyFormat($this->price);
    }

    public function getIdFromPay()
    {
        return $this->method === "card" ? $this->order_num : $this->id;
    }

    public function email(): ?string
    {
        $user = $this->user;
        return !is_null($user) && !empty($user->email) ? $user->email : null;
    }

    public function sendReceipt(): bool
    {
        $ofd = new Ofd(config('ferma.login'), config('ferma.password'));
        $this->receipt_id = $ofd->generateReceipt($this);
        return $this->save();
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Auction\Auction;
use App\Models\Auction\Step;
use App\Models\Order;
use App\Settings\ImageTrait;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Log;
use Throwable;

class OrderController extends Controller
{
    use ImageTrait;

    private const DIR = 'admin.orders.';

    public function index(Request $request)
    {
        if ($request->ajax()) {
            try {
                return datatables()->of(Order::selectRaw("*,(price + 0) AS amount")->where('exchanged', false))
                    ->editColumn('method', function ($order) {
                        return ucfirst($order->method);
                    })->editColumn('amount', function ($order) {
                        return Auction::moneyFormat($order->amount,true);
                    })->editColumn('status', function (Order $order) {
                        $class = "btn-outline-info";
                        $status = "В Ожидание";
                        if ($order->status === Order::DECLINED) {
                            $class = "btn-danger";
                            $status = "Отменено";
                        } elseif ($order->status === Order::SUCCESS) {
                            $class = "btn-success";
                            $status = "Успешно";
                        }
                        return "<button class='btn btn-sm btn-block $class'>$status</button>";
                    })->editColumn('created_at', function ($order) {
                        return $order->created_at->format('Y-m-d H:i:s');
                    })
                    ->addColumn('action', function ($order) {
                        $linkDelete = route('admin.orders.destroy', $order['id']);
                        return "<div class='btn-group btn-group-sm' role='group' aria-label='Basic example'>
                                        <button type='button'
                                                class='btn btn-outline-danger'
                                                data-toggle='modal'
                                                data-target='#resourceModal'
                                                data-action='$linkDelete'>
                                                    <i class='fa fa-trash'></i>
                                        </button>
                                    </div>";
                    })
                    ->rawColumns(['action', 'status'])
                    ->make(true);
            } catch (Throwable $exception) {
                Log::error("OrderController: " . $exception->getMessage());
            }
        }
        return view(self::DIR . 'index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $info = 'Шаг ';
        $step = Step::findOrFail($id);
        if ($step->step === 1) {
            $info .= (string)($step->step . ' Для ' . ($step->for_winner ? 'победителя' : 'остальных'));
        } elseif ($step->step === 2) {
            $info .= (string)$step->step;
            if ($step->type === Step::PRODUCT)
                $info .= ' Товар';
            elseif ($step->type === Step::MONEY)
                $info .= ' Деньги';
            elseif ($step->type === Step::BET)
                $info .= ' Ставки';
        }
        return view(self::DIR . 'edit', compact('step', 'info'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $step = Step::findOrFail($id);
        $step->update($request->only(['text']));
        return redirect()->route('admin.pages.order')->with('status', 'успешные действия !');
    }

    public function destroy($id)
    {
        $question = Order::findOrFail($id);
        $question->delete();
        return redirect()->route('admin.orders.index')->with('status', 'успешные действия !');
    }
}

resources/views/site/order/status.blade.php
@extends('layouts.site')
@push('css')
    <link rel="stylesheet" href="{{asset('site/css/coupon.css')}}">
@endpush
@section('content')
    <div style="padding: 10px 0;" class="main">
        <div class="container order__status">
            <h1>{{$status}}</h1>
            <p>{{$msg}}</p>
            <a class="btn btn-link" href="{{route('site.home')}}">Вернуться на главную страницу </a>
        </div>
    </div>
@endsection

resources/views/site/order/step_1.blade.php
@extends('layouts.site')
@push('css')
    <link rel="stylesheet" href="{{asset('site/css/coupon.css')}}">
@endpush
@section('content')
    <div style="padding: 10px 0;" class="main">
        <div class="container">
            <div style="margin: 30px 0;" class='content-block'>
                <div class='order-panel'>
                    <h1 style="font-size: 26px;">Оформление заказа</h1>
                    <h2 style="font-size: 19px;margin: 10px 0 20px 0;">Шаг 1. Создание заказа</h2>
                    <p>
                        {!! $data['text'] !!}
                    </p>
                    <div class="order-div">
                        <div class="order-desc">
                            <div class="order-desc-name">
                                <div style="font-weight: bold;color: #999;font-family: sans-serif">Номер Вашего
                                    заказа: <span style="color: #3e8ccb;">{{$data['order_num']}}</span></div>
                                <div class="order-name">
                                    <a style="color:black; text-decoration:underline;"
                                       target="_blank"
                                       href='{{route('auction.index',$data['auction_id'])}}'>{{"{$data['title']}"}}</a>
                                </div>
                            </div>
                            <div class="order-img">
                                <img style="height:116px;" src="{{asset($data['img'])}}" alt="{{$data['alt']}}">
                            </div>
                        </div>
                        <div class="order-price">
                            @if($data['winner'])
                                <div class="o-item" style="margin-top: 130px;font-weight:bold;">
                                    <div>Аукционная стоимость:</div>
                                    <div>{{$data['auction_price']}} руб.</div>
                                </div>
                            @else
                                <div class="o-item">
                                    <div>Стоимость товара:</div>
                                    <div>{{$data['full_price']}} руб.</div>
                                </div>
                                <div class="o-item">
                                    <div>Стоимость сделанных Ставок:</div>
                                    <div>{{$data['bid_price']}} руб.</div>
                                </div>
                                <div class="o-item">
                                    <div>Доставка:</div>
                                    <div>0 руб.</div>
                                </div>
                                <div class="o-item result">
                                    <div>Итого:</div>
                                    <div><span id='orderTotal'>{{$data['total_price']}}</span> руб.</div>
                                </div>
                            @endif
                        </div>
                    </div>
                    <table style='width: 100%'>
                        <tr>
                            <td style='width:50%; text-align: left;'>
                                <a class="button__app" href="{{route('auction.index',$data['auction_id'])}}">НАЗАД</a>
                            </td>
                            <td style='width:50%; text-align: right;'>
                                <a class="button__app"
                                   href="{{route('payment.auction.order',['id'=>$data['auction_id'],'step'=>'2'])}}">ПРОДОЛЖИТЬ</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/site/order/step_2.blade.php
@extends('layouts.site')
@push('css')
    <link rel="stylesheet" href="{{asset('site/css/coupon.css')}}">
@endpush
@section('content')
    <div style="padding: 10px 0;" class="main">
        <div class="container">
            <div style="margin: 30px 0;" class='content-block'>
                <div class='order-panel'>
                    <h1 style="font-size: 26px;">Оформление заказа</h1>
                    <h2 style="font-size: 19px;margin: 10px 0 20px 0;">Шаг 2. Доставка</h2>
                    <p>
                        {!! $data['text'] !!}
                    </p>
                    <table class="personal__info">
                        @if($data['type'] !== \App\Models\Auction\Step::BET)
                            <tr>
                                <td colspan="2" style="font-size:17px;">
                                    @if($data['type'] === \App\Models\Auction\Step::PRODUCT)
                                        Проверьте информацию о доставке.
                                    @else
                                        Проверьте информацию о получателе денежного перевода
                                    @endif
                                    <a style="color:#03a9f4" href="{{route('profile.personal')}}">Изменить</a></td>
                            </tr>
                            <tr>
                                <td>Фамилия:</td>
                                <td>{{$data['lname']}}</td>
                            </tr>
                            <tr>
                                <td>Имя:</td>
                                <td>{{$data['fname']}}</td>
                            </tr>
                            <tr>
                                <td>Отчество:</td>
                                <td>{{$data['mname']}}</td>
                            </tr>
                        @endif
                        @if($data['type'] === \App\Models\Auction\Step::PRODUCT)
                            <tr>
                                <td>Страна:</td>
                                <td>{{$data['country']}}</td>
                            </tr>
                            <tr>
                                <td>Индекс:</td>
                                <td>{{$data['postcode']}}</td>
                            </tr>
                            <tr>
                                <td>Регион:</td>
                                <td>{{$data['region']}}</td>
                            </tr>
                            <tr>
                                <td>Город:</td>
                                <td>{{$data['city']}}</td>
                            </tr>
                            <tr>
                                <td>Адрес:</td>
                                <td>{{$data['street']}}</td>
                            </tr>
                            <tr>
                                <td>Номер телефона:</td>
                                <td>{{$data['phone']}}</td>
                            </tr>
                        @elseif($data['type'] === \App\Models\Auction\Step::MONEY)
                            <tr>
                                <td>Платежная система:</td>
                                <td>{{$data['payment_type']}}</td>
                            </tr>
                            <tr>
                                <td>№ Карты или Счёта:</td>
                                <td>{{$data['ccnum']}}</td>
                            </tr>
                        @endif
                    </table>
                    <table style='width: 100%'>
                        <tr>
                            <td style='width:50%; text-align: left;'>
                                <a class="button__app"
                                   href="{{route('payment.auction.order',['id'=>$data['auction_id'],'step'=>'1'])}}">НАЗАД</a>
                            </td>
                            <td style='width:50%; text-align: right;'>
                                <a class="button__app"
                                   href="{{route('payment.auction.order',['id'=>$data['auction_id'],'step'=>'3'])}}">ПРОДОЛЖИТЬ</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/site/order/step_3.blade.php
@extends('layouts.site')
@push('css')
    <link rel="stylesheet" href="{{asset('site/css/coupon.css')}}">
@endpush
@section('content')
    <div style="padding: 10px 0;" class="main">
        <div class="container">
            <div style="margin: 30px 0;" class='content-block'>
                <div class='order-panel'>
                    <h1 style="font-size: 26px;">Оформление заказа</h1>
                    <h2 style="font-size: 19px;margin: 10px 0 20px 0;">Шаг 3. Оплата</h2>
                    <p class="title">Выберите способ оплаты</p>

                    <form name="buy" method="POST"
                          action="{{route('payment.auction.buy',['id' => $data['auction_id']])}}">
                        @csrf
                        @include('site.include.payment_methods')
                        <br>
                        <div>
                            <p>Номер Вашего заказа: <b
                                        id="order">{{$data['order_num']}}</b></p>
                            <p>Наименование товара: <b>{{$data['title']}}</b></p>
                            <p>Итоговая стоимость: <b id="price">{{$data['price']}}</b> <b>руб</b></p>
                        </div>
                        <br><br>
                        @if($data['email'])
                            <div>
                                <p>Кассовый чек будет отправлен в электронном виде на E-mail адрес, указанный в личном
                                    кабинете </p>
                            </div>
                        @else
                            <div>
                                <label>
                                    Укажите адрес электронный почты
                                    <input class="@error('email')is-invalid @enderror"
                                           style="width: 200px;height: 30px"
                                           type="email" name="email">
                                    @error('email')
                                    {{$message}}
                                    @enderror
                                </label>
                            </div>
                        @endif
                        {{--                        <input type="hidden" name="payment_id" id="payment_id">--}}
                        <input type="hidden" name="order_num" value="{{$data['order_num']}}">
                        <table style='width: 100%;margin-top: 25px'>
                            <tr>
                                <td style='width:50%; text-align: left;'>
                                    <a class="button__app"
                                       href="{{route('payment.auction.order',['id'=>$data['auction_id'],'step'=>'2'])}}">НАЗАД</a>
                                </td>
                                <td style='width:50%; text-align: right;'>
                                    <button class="button__app buy"
                                            type="submit">ОПЛАТИТЬ
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection