routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/


Route::group(['as' => 'admin.'], function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');
    Route::resource('auctions', 'AuctionController')->only(['destroy', 'edit', 'show']);
    Route::match(['GET', 'POST'], '/profile', 'AdminController@adminProfileChange')->name('profile');
    Route::post('products/add-group', 'ProductController@addGroup')->name('products.add_group');
    Route::get('products/{id}/duplicate', 'ProductController@duplicate')->name('products.duplicate');
    Route::post('banner/change', 'SliderController@changeBanner')->name('banner.change');
    Route::resource('products', 'ProductController')->only([
        'index', 'edit', 'update', 'create', 'store', 'destroy'
    ]);

    Route::resource('users', 'UserController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::resource('sliders', 'SliderController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('howitworks', 'HowitworkController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('questions', 'QuestionController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('reviews', 'ReviewController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('video', 'VideoController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('packages', 'PackageController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('orders', 'OrderController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::delete('bots/name/{id}/delete', 'BotController@nameDelete')->name('bots.destroy.name');
    Route::resource('bots', 'BotController')->only([
        'index', 'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::group(['as' => 'settings.', 'prefix' => 'settings'], function () {
        Route::match(['GET', 'POST'], '/mail', 'AdminController@mailConfig')->name('mail');
        Route::match(['GET', 'POST'], '/site', 'AdminController@siteConfig')->name('site');
        Route::get('/mailing', 'AdminController@mailing')->name('mailing');
        Route::match(['GET','PUT'],'/access', 'AdminController@access')->name('access');
    });
    Route::resource('role', 'RoleController')->only([
        'store', 'update', 'destroy'
    ]);
    Route::get('/mailings/{mailing}/send', 'MailingController@send')->name('mailings.send');
    Route::resource('mailings', 'MailingController')->only([
        'create', 'store', 'edit', 'update', 'destroy', 'send'
    ]);
    Route::group(['as' => 'pages.', 'prefix' => 'pages', 'namespace' => 'Pages'], function () {
        Route::post('/seo/{id}/update', 'PageController@seoUpdate')->name('seo.update');
        Route::get('/footer', 'PageController@footer')->name('footer');
        Route::post('/footer/linkOnOff', 'PageController@linkOnOff')->name('footer.linkOnOff');
        Route::post('/footer/linkPosition', 'PageController@linkPosition')->name('footer.linkPosition');
        Route::post('/footer/linkFloat', 'PageController@linkFloat')->name('footer.linkFloat');
        Route::post('/footer/crud', 'PageController@footerLinkCrud')->name('footer.crud');
        Route::get('/dynamic-page/image/browse', 'PageController@footerPageBrowseImg')->name('ckeditor.browse');
        Route::post('/dynamic-page/upload/image', 'PageController@footerPageUploadImg')->name('ckeditor.upload');
        Route::get('/home', 'PageController@homePage')->name('home');
        Route::get('/howitworks', 'PageController@howItWorksPage')->name('howitworks');
        Route::get('/reviews', 'PageController@reviewsPage')->name('reviews');
        Route::get('/feedback', 'PageController@feedbackPage')->name('feedback');
        Route::get('/coupon', 'PageController@couponPage')->name('coupon');
        Route::get('/order', 'PageController@orderPage')->name('order');
        Route::put('/update/{slug}', 'PageController@updatePage')->name('update');
        Route::put('/update_ac_content', 'PageController@updateAccordionBehindFooter')->name('updateAccordionBehindFooter');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/sitemap.xml', 'SitemapXmlController')->name('sitemap');
Route::group(['as' => 'site.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/how-it-works', 'HomeController@howItWorks')->name('how_it_works');
    Route::match(['GET', 'POST'], '/feedback', 'HomeController@feedback')->name('feedback');
    Route::get('/reviews', 'HomeController@reviews')->name('reviews');
    Route::post( '/reviews', 'HomeController@reviews')->name('reviews.store')->middleware(['auth']);
    Route::get('/coupon', 'HomeController@coupon')->name('coupon');
    Route::get('/cookie-agree', 'HomeController@cookieAgree')->name('cookie_agree');
    Route::get('/order-status', 'HomeController@orderStatus')->name('orderStatus');
    Route::get('/success', 'HomeController@success')->name('checkout.success');
    Route::get('/fail', 'HomeController@fail')->name('checkout.fail');
});

Route::group(['prefix' => '/cabinet', 'middleware' => 'auth', 'as' => 'profile.', 'namespace' => 'User'], function () {
    Route::match(['GET', 'POST'], '/', 'ProfileController@index')->name('index');
    Route::match(['GET', 'POST'], '/personal', 'ProfileController@personalData')->name('personal');
    Route::get('/balance', 'ProfileController@balance')->name('balance');
    Route::get('/orders', 'ProfileController@orders')->name('orders');
    Route::get('/auction-history', 'ProfileController@auctionsHistory')->name('auctions_history');
    Route::get('/referral-program', 'ProfileController@referralProgram')->name('referral_program');
    Route::match(['GET', 'POST'], '/code-email-confirm', 'ProfileController@codeEmailConfirm')->name('email_code_confirm');
    Route::post('/{id}/subscribe', 'ProfileController@subscribe')->name('subscribe');
});

Route::group(['as' => 'auction.',], function () {
    Route::get('/{id}/auction', 'AuctionController@auction')->name('index');
    Route::post('/{auction_id}/add-favorite', 'AuctionController@addFavorite')->name('add_favorite')->middleware('auth');
    Route::post('/{id}/auto_bid', 'AuctionController@autoBid')->name('auto_bid')->middleware(['auth', 'banned']);
    Route::post('/change-status/{id?}', 'AuctionController@changeStatus')->name('change_status');
});

Route::group(['prefix' => '/payment', 'middleware' => ['auth', 'banned'], 'as' => 'payment.', 'namespace' => 'Payments'], function () {
    Route::post('/buy-coupon', 'CouponController@buy')->name('coupon.buy');
    Route::post('/buy-auction', 'AuctionController@buy')->name('auction.buy')->middleware('order');
    Route::get('/{id}/order', 'AuctionController@order')->name('auction.order')->middleware('order');
    Route::post('/{id}/check-order', 'AuctionController@checkOrder')->name('check.order')->middleware('order');
    Route::get('/{id}/win-info', 'AuctionController@winInfo')->name('win.info')->middleware('order');
});

Route::group(['prefix' => '/reset', 'as' => 'reset.', 'namespace' => 'PasswordReset'], function () {
    Route::get('/password', 'ResetController@reset')->name('password.sms');
    Route::post('/check-phone-number', 'ResetController@checkPhone')->name('check.phone');
    Route::get('/password-change', 'ResetController@passwordChange')->name('password.change');
    Route::post('/password-change', 'ResetController@passwordChangeSuccess')->name('password.change.success');
});

Route::group(['middleware' => ['auth', 'banned']], function () {
    Route::get('/bet/{id}', 'BetController')->name('bet');
});

Route::get('/{slug?}', 'HomeController@dynamicPage')->where(['slug' => '^(?!admin.*$).*']);

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use App\Models\Balance;
use App\Models\User;
use Throwable;

class UserController extends Controller
{
    private const DIR = 'admin.users.';

    public function index(Request $request)
    {
        if ($request->ajax()) {
            try {
                return datatables()->of(User::where('is_admin', false)
                    ->select(['users.*', 'history.participation', 'history.win', 'ref.referrals_count'])
                    ->leftJoinSub("SELECT referred_by, COUNT(referral_id) AS 'referrals_count' FROM referrals GROUP BY referred_by", "ref", "users.id", "=", "ref.referred_by")
                    ->leftJoinSub("SELECT user_id, COUNT(*) AS 'participation', SUM(IF(reason = '" . Balance::WIN_AUCTION . "', 1, 0)) AS 'win' FROM balances WHERE auction_id IS NOT NULL GROUP BY user_id", "history", "users.id", "=", "history.user_id"))
                    ->editColumn('has_ban', function ($user) {
                        $link = route('admin.users.update', $user->id);
                        $class = '';
                        $active = 'false';
                        if ($user->has_ban) {
                            $class = 'active';
                            $active = 'true';
                        }
                        return "<button type='button'
                                class='btn btn-sm btn-toggle {$class}'
                                data-toggle='button'
                                aria-pressed='{$active}'
                                onclick='oNoFF(`{$link}`,{has_ban:($(this).attr(`aria-pressed`) === `true` ? 0 : 1)},`PUT`)'>
                                    <span class='handle'></span>
                                </button>";
                    })->editColumn('participation', function ($user) {
                        return (int)$user->participation;
                    })->editColumn('win', function ($user) {
                        return (int)$user->win;
                    })->editColumn('referrals_count', function ($user) {
                        return (int)$user->referrals_count;
                    })->editColumn('phone', function ($user) {
                        return $user->login();
                    })->editColumn('birthday', function ($user) {
                        return $user->birthday ? $user->birthday->format('Y-m-d') : null;
                    })->editColumn('created_at', function ($user) {
                        return $user->created_at->format('Y-m-d');
                    })->addColumn('action', function ($user) {
                        $linkDelete = route('admin.users.destroy', $user->id);
                        $linkShow = route('admin.users.edit', $user->id);
                        return "<div class='btn-group btn-group-sm' role='group' aria-label='Basic example'>
                                        <button data-href='{$linkShow}' type='button'
                                                data-toggle='modal' data-target='#cardModal'
                                                class='btn btn-info mr-1'><i class='fa fa-eye'></i></button>
                                        <button type='button' class='btn btn-danger' data-toggle='modal'
                                                data-target='#resourceModal'
                                                data-action='{$linkDelete}'>
                                                    удалить
                                        </button>
                                    </div>";
                    })->rawColumns(['has_ban', 'action'])->make(true);
            } catch (Throwable $e) {
            }
        }
        $usersInfo = User::info();
        return view(self::DIR . 'index', compact('usersInfo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws Throwable
     */
    public function edit(int $id)
    {
        if ($user = User::find($id)) {
            $roles = Role::get();
            $data = $user->userCard();
            $html = view('admin.users.card', compact('data', 'roles'))->render();
        } else {
            $html = "<div class='col-md-12'><h3 class='text-center text-danger'>Такого пользователя не существует</h3></div>";
        }
        return response(['success' => true, 'html' => $html, 'title' => 'Карточка пользователя']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, int $id)
    {
        $user = User::findOrFail($id);
        $balance = $user->balance();
        if ($request->ajax()) {
            $request->validate([
                'has_ban' => ['required', 'boolean'],
            ]);
            $user->update($request->only('has_ban'));
            $banned = User::info()['banned'];
            return response()->json(['id_name' => 'count_banned', 'change_info' => $banned]);
        }

        $request->validate([
            'role_id' => ['nullable', 'integer', 'exists:roles,id'],
            'bet' => ['sometimes', 'required', 'integer', 'min:0'],
            'bonus' => ['sometimes', 'required', 'integer', 'min:0'],
            'old_bet' => ['sometimes', 'required', 'integer', 'min:0'],
            'old_bonus' => ['sometimes', 'required', 'integer', 'min:0'],
        ]);
        if ((int)$request['old_bet'] !== $balance->bet) {
            $type = Balance::MINUS;
            $bet = abs((int)$request['old_bet'] - $balance->bet);
            if ((int)$request['old_bet'] > $balance->bet) $type = Balance::PLUS;
            $user->balanceHistory()->create([
                'type' => $type,
                'bet' => (int)$bet,
                'reason' => Balance::ADMIN,
            ]);
        }

        if ((int)$request['old_bonus'] !== $balance->bonus) {
            $type = Balance::MINUS;
            $bonus = abs((int)$request['old_bonus'] - $balance->bonus);
            if ((int)$request['old_bonus'] > $balance->bonus) $type = Balance::PLUS;
            $user->balanceHistory()->create([
                'type' => $type,
                'bonus' => (int)$bonus,
                'reason' => Balance::ADMIN,
            ]);
        }

        if ((int)$request['bet'] > 0 || (int)$request['bonus'] > 0) {
            $user->balanceHistory()->create($request->only('bet', 'bonus', 'reason'));
        }
        $user->update(['role_id' => $request->get('role_id')]);
        return redirect()->back()->with('status', 'успешные действия !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id)
    {
        $user = User::findOrFail($id);
        if (is_file(public_path($user->avatar))) unlink(public_path($user->avatar));
        $user->delete();
        return redirect()->back()->with('status', 'успешные действия !');
    }
}

resources/views/user/auctions_history.blade.php
@extends('layouts.profile')
@section('page')
    <div class="right balance tabContent">
        <div class="title">История моих аукционов</div>
        <table class="history">
            <tr>
                <th>Наименование</th>
                <th>Время завершения</th>
                <th>Ставки</th>
                <th>Бонусы</th>
                <th>Результат</th>
            </tr>
            @foreach($bids as $bid)
                <tr>
                    <td>
                        <a style="color: #1B8BCB;"
                           href="{{route('auction.index',$bid->auction_id)}}">{{$bid->auction?$bid->auction->title:"Auction N$bid->auction_id"}}</a>
                    </td>
                    <td style="white-space: nowrap;">{{$bid->auction?$bid->auction->end:$bid->created_at}}</td>
                    <td>{{$bid->bet}}</td>
                    <td>{{$bid->bonus}}</td>
                    <td>{{$bid->reason}}</td>
                </tr>
            @endforeach
        </table>
        <div class="page">
            {!! $bids->links() !!}
        </div>
    </div>
@endsection

resources/views/user/balance.blade.php
@extends('layouts.profile')
@section('page')
    <div class="right balance tabContent">
        <div class="title">Баланс</div>
        <table class="table-balance">
            <tr>
                <th>Время зачисления</th>
                <th>Ставок</th>
                <th>Бонусов</th>
                <th>Основание</th>
            </tr>
            @foreach($balance as $data)
                <tr>
                    <td style="white-space: nowrap;">{{$data->created_at}}</td>
                    <td>{{$data->bet}}</td>
                    <td>{{$data->bonus}}</td>
                    <td>{{$data->reason}}</td>
                </tr>
            @endforeach
        </table>
        <div class="page">
            {!! $balance->links() !!}
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.profile')
@section('page')
    <div class="right personal tabContent" style="font-size:14px;">
        <div class="title">Мой профиль</div>
        @if (session('status'))
            <b style="color: green">
                {{ session('status') }}
            </b>
        @endif
        <form class="content w-100" method="POST" action="{{route('profile.index')}}" style="margin-top: 50px">
            @csrf
            <div class="personal-info">
                <div class="personal-desc">
                    <p>Дата регистрации</p>
                </div>
                <div class="personal-edit">
                    <label class="personal-item">
                        <span class="personal-item-title">{{$user->created_at->format('Y-m-d')}}</span>
                    </label>
                </div>
            </div>
            <div class="personal-info">
                <div class="personal-desc">
                    <p>Изменение пароля</p>
                </div>
                <div class="personal-edit">
                    <label class="personal-item" for="current_password">
                        <span class="personal-item-title">Старый пароль:</span>
                        <input class="@error('current_password')is-invalid @enderror" required type="password"
                               name="current_password" id="current_password">
                    </label>
                    @error('current_password')
                    <small style="color: red;width: 100%;text-align: center;">
                        {{$message}}
                    </small>
                    @enderror
                    <label class="personal-item" for="new_password">
                        <span class="personal-item-title">Новый пароль:</span>
                        <input class="@error('new_password')is-invalid @enderror" required type="password"
                               name="new_password" id="new_password" placeholder="Не менее 8 символов">
                    </label>
                    @error('new_password')
                    <small style="color: red;width: 100%;text-align: center;">
                        {{$message}}
                    </small>
                    @enderror
                    <label class="personal-item" for="new_confirm_password">
                        <span class="personal-item-title">Подтвердите пароль:</span>
                        <input class="@error('new_confirm_password')is-invalid @enderror" required type="password"
                               name="new_confirm_password" id="new_confirm_password">
                    </label>
                    @error('new_confirm_password')
                    <small style="color: red;width: 100%;text-align: center;">
                        {{$message}}
                    </small>
                    @enderror
                    <label class="personal-item">
                        <span class="personal-item-title"></span>
                        <button class="button__app" type="submit">Сохранить</button>
                    </label>
                </div>
            </div>
            <div class="personal-info">
                <div class="personal-desc">
                    <p>Управление рассылками</p>
                </div>
                <div class="personal-edit">
                    <label class="personal-item">
                        <span class="personal-item-title">уведомлять по e-mail:</span>
                    </label>
                    @foreach($mailings as $mailing)
                        <label class="personal-item">
                            <span class="personal-item-title"> {{$mailing->title}}:</span>
                            <input type="checkbox"
                                   onclick='oNoFF("{{route('profile.subscribe',$mailing->id)}}",{subscribe:+($(this).prop("checked")),},"POST")'
                                   @if($user->subscribe->where('id',$mailing->id)->first()) checked
                                   @endif name="subscribe" value="{{$mailing->id}}">
                        </label>
                    @endforeach

                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/user/orders.blade.php
@extends('layouts.profile')
@section('page')
    <div class="right orders tabContent">
        <div class="title">Мои заказы</div>
        <div id="orders">
            @foreach($orders as $order)
                <div class="item">
                    <div class="block__img">
                        <a href="{{$order->auction_id ? route('auction.index',$order->auction_id) : '#'}}">
                            <img src="{{$order->auction ? asset($order->auction->img_1):asset("site/img/no-image.jpg")}}"
                                 alt="">
                        </a>
                    </div>
                    <div class="block__content">
                        <p><b>Наименование:</b>{{$order->product_name}}</p>
                        <p><b>&#8470; заказа:</b>{{$order->order_num}}</p>
                        <p><b>Цена:</b>{{App\Models\Auction\Auction::moneyFormat($order->price,true,' руб')}}</p>
                        <p><b>Дата:</b>{{$order->created_at->format("Y/m/d")}}</p>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="page">
            {!! $orders->links() !!}
        </div>
    </div>
@endsection

resources/views/user/referral_program.blade.php
@extends('layouts.profile')
@section('page')
    <div class="right referal tabContent">
        <div class="title">Реферальная программа</div>
        <p style="text-align: center;font-weight: bold; ">
            Получайте бонусы по нашей реферальной программе, используйте их в аукционах
            и выигрывайте все что Вам нравится.</p>
        @if($user->fullProfile() && $user->couponOrder()->count())
            <p style="border-bottom: 3px solid #1B8BCB; margin:10px;">
                Разместите эту ссылку на своей странице в
                социальных сетях, на различных форумах, сайтах или просто отправьте своему другу.
                Он должен будет вставить эту ссылку в адресную строку браузера и зайти к нам на сайт.
                Затем пройти полную регистрацию, заполнить свои персональные данные и приобрести любой пакет
                ставок. После этого Вам будут зачислены Бонусы в размере 50%
                от количества Ставок купленных Вашим рефералом в первый раз.
            </p>
            <b style="margin-top: 15px;">Реферальная ссылка:
                <input id="ref-link" class="ref-link" style="padding: 5px; font-weight: normal;" type="text"
                       value="{{route('site.home',['ref'=>$user->id])}}">
                <input id="copyButton" class="button__app" style="margin-left: 10px;"
                       type="button" value="КОПИРОВАТЬ">
            </b>
            <table>
                <tr>
                    <th>Время зачисления</th>
                    <th>Имя реферала</th>
                    <th>Бонусов</th>
                </tr>
                @foreach($referrals as $referral)
                    <tr>
                        <td>{{$referral->pivot->updated_at}}</td>
                        <td>{{$referral->nickname}}</td>
                        <td>{{$referral->pivot->referral_bonus}}</td>
                    </tr>
                @endforeach
            </table>
            <div class="page">
                {!! $referrals->links() !!}
            </div>
        @else
            <div class="list-ref">
                <p>Чтобы получить реферальную ссылку, необходимо заполнить свои
                    <a href="{{route('profile.personal')}}" style="color: #1B8BCB;">персональные данные</a>,
                    помеченные знаком *, и приобрести любой
                    <a href="{{route('site.coupon')}}" style="color: #1B8BCB; ">пакет ставок</a>.
                </p>
            </div>
        @endif
    </div>
@endsection