routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/


Route::group(['as' => 'admin.'], function () {
    Route::get('/', 'AdminController@dashboard')->name('dashboard');
    Route::resource('auctions', 'AuctionController')->only(['destroy', 'edit', 'show']);
    Route::match(['GET', 'POST'], '/profile', 'AdminController@adminProfileChange')->name('profile');
    Route::post('products/add-group', 'ProductController@addGroup')->name('products.add_group');
    Route::get('products/{id}/duplicate', 'ProductController@duplicate')->name('products.duplicate');
    Route::post('banner/change', 'SliderController@changeBanner')->name('banner.change');
    Route::resource('products', 'ProductController')->only([
        'index', 'edit', 'update', 'create', 'store', 'destroy'
    ]);

    Route::resource('users', 'UserController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::resource('sliders', 'SliderController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('howitworks', 'HowitworkController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('questions', 'QuestionController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('reviews', 'ReviewController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('video', 'VideoController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('packages', 'PackageController')->only([
        'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::resource('orders', 'OrderController')->only([
        'index', 'edit', 'update', 'destroy'
    ]);
    Route::delete('bots/name/{id}/delete', 'BotController@nameDelete')->name('bots.destroy.name');
    Route::resource('bots', 'BotController')->only([
        'index', 'create', 'store', 'edit', 'update', 'destroy'
    ]);
    Route::group(['as' => 'settings.', 'prefix' => 'settings'], function () {
        Route::match(['GET', 'POST'], '/mail', 'AdminController@mailConfig')->name('mail');
        Route::match(['GET', 'POST'], '/site', 'AdminController@siteConfig')->name('site');
        Route::get('/mailing', 'AdminController@mailing')->name('mailing');
        Route::match(['GET','PUT'],'/access', 'AdminController@access')->name('access');
    });
    Route::resource('role', 'RoleController')->only([
        'store', 'update', 'destroy'
    ]);
    Route::get('/mailings/{mailing}/send', 'MailingController@send')->name('mailings.send');
    Route::resource('mailings', 'MailingController')->only([
        'create', 'store', 'edit', 'update', 'destroy', 'send'
    ]);
    Route::group(['as' => 'pages.', 'prefix' => 'pages', 'namespace' => 'Pages'], function () {
        Route::post('/seo/{id}/update', 'PageController@seoUpdate')->name('seo.update');
        Route::get('/footer', 'PageController@footer')->name('footer');
        Route::post('/footer/linkOnOff', 'PageController@linkOnOff')->name('footer.linkOnOff');
        Route::post('/footer/linkPosition', 'PageController@linkPosition')->name('footer.linkPosition');
        Route::post('/footer/linkFloat', 'PageController@linkFloat')->name('footer.linkFloat');
        Route::post('/footer/crud', 'PageController@footerLinkCrud')->name('footer.crud');
        Route::get('/dynamic-page/image/browse', 'PageController@footerPageBrowseImg')->name('ckeditor.browse');
        Route::post('/dynamic-page/upload/image', 'PageController@footerPageUploadImg')->name('ckeditor.upload');
        Route::get('/home', 'PageController@homePage')->name('home');
        Route::get('/howitworks', 'PageController@howItWorksPage')->name('howitworks');
        Route::get('/reviews', 'PageController@reviewsPage')->name('reviews');
        Route::get('/feedback', 'PageController@feedbackPage')->name('feedback');
        Route::get('/coupon', 'PageController@couponPage')->name('coupon');
        Route::get('/order', 'PageController@orderPage')->name('order');
        Route::put('/update/{slug}', 'PageController@updatePage')->name('update');
        Route::put('/update_ac_content', 'PageController@updateAccordionBehindFooter')->name('updateAccordionBehindFooter');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/sitemap.xml', 'SitemapXmlController')->name('sitemap');
Route::group(['as' => 'site.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/how-it-works', 'HomeController@howItWorks')->name('how_it_works');
    Route::match(['GET', 'POST'], '/feedback', 'HomeController@feedback')->name('feedback');
    Route::get('/reviews', 'HomeController@reviews')->name('reviews');
    Route::post( '/reviews', 'HomeController@reviews')->name('reviews.store')->middleware(['auth']);
    Route::get('/coupon', 'HomeController@coupon')->name('coupon');
    Route::get('/cookie-agree', 'HomeController@cookieAgree')->name('cookie_agree');
    Route::get('/order-status', 'HomeController@orderStatus')->name('orderStatus');
    Route::get('/success', 'HomeController@success')->name('checkout.success');
    Route::get('/fail', 'HomeController@fail')->name('checkout.fail');
});

Route::group(['prefix' => '/cabinet', 'middleware' => 'auth', 'as' => 'profile.', 'namespace' => 'User'], function () {
    Route::match(['GET', 'POST'], '/', 'ProfileController@index')->name('index');
    Route::match(['GET', 'POST'], '/personal', 'ProfileController@personalData')->name('personal');
    Route::get('/balance', 'ProfileController@balance')->name('balance');
    Route::get('/orders', 'ProfileController@orders')->name('orders');
    Route::get('/auction-history', 'ProfileController@auctionsHistory')->name('auctions_history');
    Route::get('/referral-program', 'ProfileController@referralProgram')->name('referral_program');
    Route::match(['GET', 'POST'], '/code-email-confirm', 'ProfileController@codeEmailConfirm')->name('email_code_confirm');
    Route::post('/{id}/subscribe', 'ProfileController@subscribe')->name('subscribe');
});

Route::group(['as' => 'auction.',], function () {
    Route::get('/{id}/auction', 'AuctionController@auction')->name('index');
    Route::post('/{auction_id}/add-favorite', 'AuctionController@addFavorite')->name('add_favorite')->middleware('auth');
    Route::post('/{id}/auto_bid', 'AuctionController@autoBid')->name('auto_bid')->middleware(['auth', 'banned']);
    Route::post('/change-status/{id?}', 'AuctionController@changeStatus')->name('change_status');
});

Route::group(['prefix' => '/payment', 'middleware' => ['auth', 'banned'], 'as' => 'payment.', 'namespace' => 'Payments'], function () {
    Route::post('/buy-coupon', 'CouponController@buy')->name('coupon.buy');
    Route::post('/buy-auction', 'AuctionController@buy')->name('auction.buy')->middleware('order');
    Route::get('/{id}/order', 'AuctionController@order')->name('auction.order')->middleware('order');
    Route::post('/{id}/check-order', 'AuctionController@checkOrder')->name('check.order')->middleware('order');
    Route::get('/{id}/win-info', 'AuctionController@winInfo')->name('win.info')->middleware('order');
});

Route::group(['prefix' => '/reset', 'as' => 'reset.', 'namespace' => 'PasswordReset'], function () {
    Route::get('/password', 'ResetController@reset')->name('password.sms');
    Route::post('/check-phone-number', 'ResetController@checkPhone')->name('check.phone');
    Route::get('/password-change', 'ResetController@passwordChange')->name('password.change');
    Route::post('/password-change', 'ResetController@passwordChangeSuccess')->name('password.change.success');
});

Route::group(['middleware' => ['auth', 'banned']], function () {
    Route::get('/bet/{id}', 'BetController')->name('bet');
});

Route::get('/{slug?}', 'HomeController@dynamicPage')->where(['slug' => '^(?!admin.*$).*']);

resources/views/site/include/auction.blade.php
<div data-auction-id="{{$auction['id']}}"
     class="card active">
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_ACTIVE || $auction['status'] === \App\Models\Auction\Auction::STATUS_PENDING)
        <div class="favorites @if($auction['top']) top @endif">
            <span @if($auction['favorite'] || $auction['top']) class="active" @endif></span>
        </div>
    @endif
    <a href="{{route('auction.index',$auction['id'])}}">
        @if($auction['my_win'] && $auction['status'] === \App\Models\Auction\Auction::STATUS_ERROR)
            <img class="product-img"
                 src="{{asset('site/img/settings/error.jpg')}}"
                 alt="error">
        @else
            <img class="product-img"
                 src="{{$auction['images'][0]['img']}}"
                 alt="{{$auction['images'][0]['alt']}}">
        @endif
    </a>
    <div class="name">
        <a title="{{$auction['title']}}" href="{{route('auction.index',$auction['id'])}}">{{$auction['title']}}</a>
    </div>
    <div class="short__desc">
        <span>{{$auction['short_desc']}}</span>
    </div>
    <div class="info">
        <div class="con-tooltip top">
            <div class="circl">
                <p title="Время прибавляемое к таймеру после ставки">{{$auction['bid_seconds']}}<br>
                    <span>сек</span>
                </p>
            </div>
            <div class="tooltip first">
                <p>Время прибавляемое к таймеру после ставки</p>
            </div>
        </div>
        <div class="con-tooltip top">
            <div class="circl ">
                <p title="Шаг ставки">{{$auction['step_price_info']}}<br><span>коп</span></p>
            </div>
            <div class="tooltip second">
                <p>Шаг ставки</p>
            </div>
        </div>
        @if($auction['exchange'])
            <div class="con-tooltip top">
                <div class="circl">
                    <img title="Возможность получить вместо выигранного товара &quot;Ставки&quot;"
                         src="{{asset('site/img/arrow_black.png')}}" alt="">
                </div>

                <div class="tooltip three">
                    <p>Возможность получить вместо выигранного товара "Ставки"</p>
                </div>
            </div>
        @endif

        @if($auction['buy_now'])
            <div class="con-tooltip top">
                <a class="buy__auction @if($auction['my_win'] && $auction['exchange']) my___win @endif"
                   data-id="{{$auction['id']}}"
                   href="{{route('payment.auction.order',['id'=>$auction['id'],'step'=>'1'])}}">
                    <div class="circl">
                        <img title="Купить сейчас за {{$auction['my_win']?$auction['price']:$auction['full_price']}} ₽"
                             src="{{asset('site/img/if_business_finance_money-05_2784238.png')}}"
                             alt="">
                    </div>
                </a>
            </div>
        @endif
    </div>
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_PENDING)
        <div class="inf">
            <p class="timer">До начала <span class="to__start"
                                             data-countdown="{{$auction['start']}}"></span>
            </p>
        </div>
        <div class="btn">
            <span class="price">{{$auction['start_price']}} ₽</span>
            <button>Скоро</button>
        </div>
    @endif
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_ACTIVE)
        <div class="inf">
            <p class="winner">{{$auction['winner']}}</p>
            <p class="timer">
                <span data-countdown="{{$auction['step_time']}}"></span>
            </p>
        </div>
        <div class="btn active">
            <span class="price">{{$auction['price']}} ₽</span>
            <button class="@if((bool)$auction['autoBid']) disabled @endif">Ставка</button>
        </div>
    @endif
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED || $auction['status'] === \App\Models\Auction\Auction::STATUS_ERROR)
        @if(is_null($auction['winner']))
            <div class="lenta not__win">Не состоялся</div>
            <div class="inf"></div>
            <div class="btn not__win">
                <span class="price">{{$auction['price']}} ₽</span>
                <button>{{$auction['price']}} ₽</button>
            </div>
        @else
            <div class="inf">
                @if(($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED || $auction['status'] === \App\Models\Auction\Auction::STATUS_ERROR))
                    @if($auction['my_win'] && $auction['error'])
                    @else
                        <p class="winner">{{$auction['winner']}}</p>
                        <p class="price">{{$auction['price']}} ₽</p>
                    @endif
                @endif
            </div>
            @if(!$auction['my_win'] || $auction['ordered'])
                <div class="lenta close">ЗАВЕРШЕН</div>
                <div class="btn close">
                    <span class="price">{{$auction['price']}} ₽</span>
                    <button>Аукцион закрыт</button>
                </div>
            @else
                @if($auction['status'] === \App\Models\Auction\Auction::STATUS_ERROR)
                    <div class="btn error">
                        <button>ОШИБКА</button>
                    </div>
                @else
                    <div class="btn win">
                        <span class="price">{{$auction['price']}} ₽</span>
                        <a data-id="{{$auction['id']}}"
                           href="{{route('payment.auction.order',['id'=>$auction['id'],'step'=>'1'])}}"
                           class="buy__auction @if($auction['my_win'] && $auction['exchange']) my___win @endif">Оформить заказ</a>
                    </div>
                @endif
            @endif
        @endif
    @endif
</div>

resources/views/site/include/auctions.blade.php
@foreach($auctions as $auction)
    @include('site.include.auction')
@endforeach
<div class="w-100 mt-25">
    {!! $auctions->render() !!}
</div>

resources/views/site/include/bonus_modal.blade.php
<div class="notify__modal">
    <div class="notify notify__item">
        <div class="bonus__30"></div>
        <button class="notify__modal__btn__close btn__close">X</button>
        <div class="notify__modal__body">
            <h3>Заполни персональные данные и получи на счет</h3>
            <h2><span>{{$bonus}} </span>Бонусов</h2>
        </div>
        <div class="notify__modal__footer">
            <a href="{{route('profile.personal')}}" class="button__app">Получить</a>
        </div>
    </div>
</div>

resources/views/site/include/info.blade.php
@if($auction['error'])
    <h1 style="text-align: center">
        АУКЦИОН ЗАБЛОКИРОВАН
    </h1>
    <div class="error-box">
        <h3>Злоумышленники пытались воздействовать на ход игры данного аукциона.</h3>
        <div>
            <h4>Вами поставлено {{$auction['bet']}} Ставок и {{$auction['bonus']}} Бонусов</h4>
            <h3> Все Ставки и Бонусы будут возвращены.</h3>
        </div>
        <h3>Приносим извинения за неудобства </h3>
    </div>
@else
    <p class="title">
        {{$auction['title']}}
    </p>
    <div class="info">
        <div class="circl">
            <p title="Время прибавляемое к таймеру после ставки">
                {{$auction['bid_seconds']}}
                <br><span>сек</span>
            </p>
        </div>
        <div class="circl">
            <p title="Шаг ставки">{{$auction['step_price_info']}}<br><span>коп</span></p>
        </div>
        @if($auction['exchange'])
            <div class="circl">
                <img title='Возможность получить вместо выигранного товара "Ставки"'
                     src="{{asset('site/img/reload-white.png')}}" alt="">
            </div>
        @endif
        @if($auction['buy_now'])
            <div class="circl">
                <a class="buy__auction @if($auction['my_win'] && $auction['exchange']) my___win @endif"
                   data-id="{{$auction['id']}}"
                   href="{{route('payment.auction.order',['id'=>$auction['id'],'step'=>'1'])}}">
                    <img style="padding-left: 2px" title="Купить сейчас за {{$auction['full_price']}} ₽"
                         src="{{asset('site/img/korzina-white.png')}}"
                         alt="">
                </a>
            </div>
        @endif
    </div>
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_PENDING)
        <div class="inf__pending">
            <p> Аукцион начнется через</p>
            <span class="to__start countdown"
                  data-countdown="{{$auction['start']}}"></span>
        </div>
    @endif
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_ACTIVE)
        <p class="winner">{{$auction['winner']}}</p>
        <div class="inf__active">
            <span class="price">{{$auction['price']}} ₽</span>
            <span class="countdown" data-countdown="{{$auction['step_time']}}"></span>
            <button class="@if((bool)$auction['autoBid']) disabled @endif">Ставка</button>
        </div>
        <!-- Сюда вставляется автоставки -->
        <form class="auto__bid" method="POST" action="{{route('auction.auto_bid',$auction['id'])}}">
            @csrf

            <input class="auto__bid_inp" min="0" type="number" name="count" value="{{$auction['autoBid']}}"
                   placeholder="введите ставку">
            <button type="submit" class="auto__bid_btn">
                автоставка
            </button>
        </form>
    @endif
    @if($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED || $auction['status'] === \App\Models\Auction\Auction::STATUS_ERROR)
        @if(is_null($auction['winner']))
            <p class="winner">Не состоялся</p>
        @else
            <div class="inf__finish">
                <p class="winner">Победитель: {{$auction['winner']}}</p>
                <p class="price__for_winner">Цена для победителя аукциона</p>
                <p class="price">{{$auction['price']}} ₽</p>
            </div>
            @if($auction['my_win'])
                <div class="btn win">
                    <a class="buy__auction @if($auction['my_win'] && $auction['exchange']) my___win @endif"
                       data-id="{{$auction['id']}}"
                       href="{{route('payment.auction.order',['id'=>$auction['id'],'step'=>'1'])}}">Оформить заказ</a>
                </div>
            @endif
        @endif
    @endif

    @if($auction['buy_now'] && !$auction['my_win'])
        <div
                class="buy__now @if(!($auction['status'] === \App\Models\Auction\Auction::STATUS_ACTIVE) && !($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED)) mt-100 @elseif(($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED) && !$auction['my_win']) mt-90 @endif ">
            <span class="buy__now_price">{{$auction['full_price']}} ₽</span>
            <a href="{{route('payment.auction.order',['id'=>$auction['id'],'step'=>'1'])}}" class="buy__auction buy__now_btn">
                купить сейчас
            </a>
        </div>
        <p class="info__text"
           @if($auction['status'] === \App\Models\Auction\Auction::STATUS_FINISHED) style="margin: 0" @endif>Цена с
            учетом
            сделанных Вами
            ставок</p>
    @endif
    <div class="info__my__bid">
        <div class="item">
            <span>Поставлено Ставок</span><span class="bet">{{$auction['bet']}}</span>
        </div>
        <div class="item">
            <span> Поставлено Бонусов</span><span
                    class="bonus">{{$auction['bonus']}}</span>
        </div>
    </div>
    <div class="log-bid">
        <table class="scrolldown">
            <thead>
            <tr>
                <th>Цена</th>
                <th>Участники</th>
                <th>Время</th>
            </tr>
            </thead>
            <tbody>
            @foreach($auction['bids'] as $bid)
                <tr>
                    <td>{{$bid['price']}}</td>
                    <td>{{$bid['nickname']}}</td>
                    <td>{{$bid['created_at']}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endif

resources/views/site/include/info_modal.blade.php
<div class="notify__modal notify__info">
    <div class="notify__item">
        <button class="notify__modal__btn__close btn__close">X</button>
        <div class="notify__modal__body">
          <div class="info">
              <span>{{$message}}</span>
          </div>
        </div>
    </div>
</div>

resources/views/site/include/payment_methods.blade.php
<div class="payment">
    @foreach(\App\Settings\SiteSetting::paymentGroup() as $group => $payments)
        @switch($group)
            @case("card")
            <div class="payment-type">
                <label class="app-style-input">
                    <input type="radio" name="payment_group" value="{{$group}}">
                    <span></span>
                </label>
                <h4>Банковские карты</h4>
                <ul class="payment-lists">
                    @foreach($payments as $payment)
                        <li data-id="{{$payment['id']}}">
                            <img src="{{asset($payment['img'])}}" alt="{{$payment['value']}}">
                        </li>
                    @endforeach
                </ul>
            </div>
            @break

            @case("yoo-money")
            <div class="payment-type">
                <label class="app-style-input">
                    <input type="radio" name="payment_group" value="{{$group}}">
                    <span></span>
                </label>
                <h4>ЮMoney кошелек</h4>
                <ul class="payment-lists">
                    @foreach($payments as $payment)
                        <li data-id="{{$payment['id']}}">
                            <img src="{{asset($payment['img'])}}" alt="{{$payment['value']}}">
                        </li>
                    @endforeach
                </ul>
            </div>
            @break
            @case("qiwi")
            <div class="payment-type">
                <label class="app-style-input">
                    <input type="radio" name="payment_group" value="{{$group}}">
                    <span></span>
                </label>
                <h4>Qiwi кошелек</h4>
                <ul class="payment-lists">
                    @foreach($payments as $payment)
                        <li data-id="{{$payment['id']}}">
                            <img src="{{asset($payment['img'])}}" alt="{{$payment['value']}}">
                        </li>
                    @endforeach
                </ul>
            </div>
            @break
            @case("perfect-money")
            <div class="payment-type">
                <label class="app-style-input">
                    <input type="radio" name="payment_group" value="{{$group}}">
                    <span></span>
                </label>
                <h4>Perfect Money</h4>
                <ul class="payment-lists">
                    @foreach($payments as $payment)
                        <li data-id="{{$payment['id']}}">
                            <img src="{{asset($payment['img'])}}" alt="{{$payment['value']}}">
                        </li>
                    @endforeach
                </ul>
            </div>
            @break

            @case("tel-operators")
            <div class="payment-type">
                <label class="app-style-input">
                    <input type="radio" name="payment_group" value="{{$group}}">
                    <span></span>
                </label>
                <h4>Сотовые операторы</h4>
                <ul class="payment-lists">
                    @foreach($payments as $payment)
                        <li data-id="{{$payment['id']}}">
                            <img src="{{asset($payment['img'])}}" alt="{{$payment['value']}}">
                        </li>
                    @endforeach
                </ul>
            </div>
            @break
        @endswitch
    @endforeach
</div>

resources/views/site/include/svg_loader.blade.php
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="display: none">
    <defs>
        <filter id="goo">
            <fegaussianblur in="SourceGraphic" stddeviation="15" result="blur"></fegaussianblur>
            <fecolormatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 30 -10" result="goo"></fecolormatrix>
            <feblend in="SourceGraphic" in2="goo"></feblend>
        </filter>
    </defs>
</svg>

resources/views/site/include/winner_modal.blade.php
<div class="notify__modal">
    <div class="notify__item">
        <div class="notify__modal__body">
            <div class="win__info_container">
                <div class="image__container">
                    <p>{{$data['title']}}</p>
                    <img src="{{asset($data['image'])}}" alt="{{$data['alt']}}">
                </div>
                <div class="info__container">
                    <div class="info__container_absolute">
                        <span
                                style="width: 24px;height: 8px;color: #575656;font-size: 14px;font-weight: 400;;position: absolute;top: 110px;">или</span>
                        <div class="left__item">
                            <p>{{$data['price']}}</p>
                            <span style="font-size: 23px;font-weight: 400;padding: 5px;">рублей</span>
                            <a href="{{route('payment.auction.order',['id'=>$data['id'],'step'=>'1'])}}">оплатить</a>
                            <span style="margin:75px 0px 15px 0px;width: 120px;font-size: 14px;font-weight: 400;">После оплаты мы отправим Вам этот заказ </span>
                            <img style="width: 54px;height: 61px;" src="{{asset('site/img/gift.png')}}" alt="gift">
                        </div>
                        <div class="right__item">
                            <p>{{$data['bet']}}</p>
                            <span style="font-size: 23px;font-weight: 400;padding: 5px;">ставок</span>
                            <a href="{{route('payment.win.info',['id'=>$data['id'],'exchange'=>true])}}">получить</a>
                            <div class="bonus__item">
                                <h2>+ {{$data['bonus']}}  </h2>
                                <h3>Бонусов </h3>
                            </div>
                            <span style="width: 110px;font-size: 14px;font-weight: 400;">
                                На эти Ставки и Бонусы Вы сможете  выгрывать еще больше призов!</span>
                            <img style="width: 126px;height: 71px;" src="{{asset('site/img/gifts.png')}}" alt="gifts">
                        </div>
                        <div class="bottom__item">
                            <p>СОВЕТ: получить Ставки и Бонусы намного выгодней покупки товара </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>